import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  folder1Sidebar: [
    {
      type: 'category',
      label: 'folder1',
      link: {
        type: 'generated-index',
        slug: '/', 
        title: 'folder1',
        description: 'a folder',
      },
      items: [{ type: 'autogenerated', dirName: '.' }],
      collapsed: false,
    },
  ],
};

export default sidebars;